wmde/banner-server

build/app/Dockerfile, docker-compose.yml
Add target name to Dockerfile (used by docker-compose).
Remove network definition from docker-compose file. Network name was not
used by the services and at the moment there is no need to share the
network with other installations (e.g. FundraisingFrontend).
=> Fix Docker setup

composer.json, composer.lock
Remove fun-validators (we'll use Symfony Validation if needed)
Remove pse-log-double (not used)
Remove vfsStream (we'll add it back when we need it)
Remove codeceptions/specify - not used and slows down tests anyway.
Update version requirements
=> Remove unneeded packages

config/services.yaml, src/Entity/BannerSelection/CampaignCollection.php
Symfony excludes directories named "Entity" from being auto-wired by
default because it assumes these are Doctrine entity classes. Since this
is not the case for the scope of this application, this exclusion is
removed.
=> Fix issues with Symfony auto-wiring

src/UseCase/BannerSelection/BannerSelection.php, src/UseCase/BannerSelection/BannerSelectionUseCase.php
To make the two different results of BannerSelectionUseCase more
explicit, use two different construction methods and make constructor
private.
Also, ensure that each "version" of the BannerSelection has the proper
value and matches its type definition.
A Follow-up for #14
=> Improve construction of BannerSelection

src/Controller/BannerSelectionController.php, tests/Unit/Controller/BannerSelectionControllerTest.php
It looks like HTTP 204 is cached relatively aggressively by some
browsers and the content type is not set properly, so we should move to
using HTTP 200 and deliver some placeholder content.
https://phabricator.wikimedia.org/T224296
=> Use HTTP 200 response rather than HTTP 204

src/Controller/BannerSelectionController.php, src/Entity/BannerSelection/Campaign.php, src/Entity/Visitor.php, src/UseCase/BannerSelection/BannerSelectionUseCase.php, src/Utils/CampaignConfigurationLoader.php, tests/Fixtures/CampaignFixture.php, tests/Fixtures/VisitorFixture.php, tests/Fixtures/campaigns/campaigns.yml, tests/Unit/Entity/BannerSelection/CampaignCollectionTest.php, tests/Unit/Entity/BannerSelection/CampaignTest.php, tests/Unit/Entity/VisitorTest.php, tests/Unit/UseCase/BannerSelection/BannerSelectionUseCaseTest.php, tests/Unit/Utils/CampaignConfigurationLoaderTest.php
Add categories to campaigns and visitors to check if visitors have interacted with banners and suppress banner display when visitor has an interaction cookie.
This is for https://phabricator.wikimedia.org/T243757
=> Add categories to campaigns and visitors

src/Controller/BannerSelectionController.php, src/Entity/BannerSelection/Campaign.php, src/Entity/BannerSelection/CampaignCollection.php, src/Entity/Visitor.php, src/UseCase/BannerSelection/BannerSelectionUseCase.php, src/Utils/CampaignConfigurationLoader.php, tests/Fixtures/CampaignFixture.php, tests/Fixtures/VisitorFixture.php, tests/Fixtures/campaigns/broken_bucket_campaign.yml, tests/Fixtures/campaigns/broken_data_campaign.yml, tests/Fixtures/campaigns/broken_displayWidth_campaign.yml, tests/Fixtures/campaigns/campaigns.yml, tests/Unit/Entity/BannerSelection/CampaignCollectionTest.php, tests/Unit/Entity/BannerSelection/CampaignTest.php, tests/Unit/Entity/VisitorTest.php, tests/Unit/UseCase/BannerSelection/BannerSelectionUseCaseTest.php, tests/Unit/Utils/CampaignConfigurationLoaderTest.php
Adds 2 private fields to the campaign class.
The 2 values are the range of vieport width in which this campaign should be active.
https://phabricator.wikimedia.org/T253535
=> Handle client viewport width for campaigns

.travis.yml, phpstan.prod.neon
Instead of downloading a PHPStan version, use the same Docker image we
use in the Makefile
=> Use custom PHPStan in Travis

src/Entity/BannerSelection/Campaign.php, tests/Fixtures/BucketFixture.php, tests/Fixtures/CampaignFixture.php, tests/Fixtures/VisitorFixture.php, tests/Unit/Entity/BannerSelection/CampaignTest.php, tests/Unit/UseCase/BannerSelection/BannerSelectionUseCaseTest.php
This removes the 1px gap between mobile and desktop banners.
It also add a test to make sure that the correct banner is selected when there is a mobile and desktop campaign running at the same time.
=> Remove 1px gap on banner selection by width

src/Controller/AbstractCookieController.php, src/Controller/BannerSelectionController.php
The `ParameterBag::get` method has a mixed return type, while our
the functions expect string or null values. We cast the inputs to
strings to avoid warnings from static analysis.
=> Cast string inputs to int

Makefile, composer.json, composer.lock
Ignoring the platform requirements will install the PHP 8 compatible
version of psr/cache, leading to incompatibilities with PHP 7.
This change makes the cache library and supported PHP version explicit
and removes the harmful parameter from the Makefile
=> Remove --ignore-platform-reqs

build/app/Dockerfile, docker-compose.debug.yml
Update PHP to 8 and Xdebug to 3
This update fixes our CI failures while building the Docker image. The
newest Debian version ("bullseye") has a problem when building PHP, so
we fix the underlying version to the previous one ("buster").
The CI environment seems to be fine, but we haven't tested the server
yet and it still runs on PHP 7.4 in production.
Our current Symfony version 4 might not be compatible with PHP 8 so this
is a preliminary commit to avoid the piling-up of failed dependabot pull
requests.
=> Update PHP and Xdebug

composer.json, composer.lock, symfony.lock
Since we only deliver JavaScript, we don't need to use DOM-Crawler and
CSS selectors in our dev-dependencies. This will prevent Dependabot from
trying to upgrade unnecessary dependencies.
=> Remove Symfony testing libraries

config/routes.yaml, config/services.yaml, src/Controller/MaybeLaterController.php
Hitting maybe later on a banner's soft close should now add a 6 hour cookie on the banner server
Ticket: https://phabricator.wikimedia.org/T352509
=> Add Maybe Later cookie controller

config/services.yaml
The interval was invalid, leading to errors instead of a cookie being
set when the donor clicks on "maybe later" in the soft-close banner in
wikipedia.de
=> Fix broken "maybe later" cookie interval

composer.lock
I was getting the error "Could not resolve host: flex.symfony.com" when
trying to run `composer install` (or `make install-php`)
The issue and the fix are known:
https://symfony.com/blog/the-old-flex-infrastructure-is-shutting-down
https://symfony.com/blog/upgrade-flex-on-your-symfony-projects
=> Update Symfony flex dependency

build/app/Dockerfile, config/routes.yaml, src/Controller/AbstractCookieController.php, src/Controller/AbstractCookieControllerWithFixedLifetime.php, src/Controller/AlreadyDonatedController.php, src/Controller/BannerClosedController.php, src/Controller/DonationFinishedController.php, src/Controller/MaybeLaterController.php, tests/Unit/Controller/AlreadyDonatedControllerTest.php, tests/Utils/TestCookieController.php
- Update PHP to 8.3
- Refactor AbstractCookieController
- Add new route for "Already donated" cookie: `/already-donated`
https://phabricator.wikimedia.org/T375609
https://phabricator.wikimedia.org/T376792
=> Add route for "Already Donated" cookie

composer.json, phpstan.neon.dist, phpstan.prod.neon, tests/bootstrap.php
- fix potential deprecation warnings
=> Require Symfony v7.2

phpstan.neon.dist, phpstan.prod.neon, src/Entity/Visitor.php, src/Utils/CampaignConfigurationLoader.php, tests/Unit/EventListener/ExceptionListenerTest.php
The `CampaignConfigurationLoader` is responsible for turning the untyped array that comes out of parsing a YAML file into a properly typed class. Therefore the array values need to be a bit "sloppy" (i.e. `mixed`). But it fixes the PHPStan errors, so we don't need an exception for them.
=> Add types for arrays

public/index.php
This ensures that when cleaning up old deploys, the `deploy` user can
delete old caches and temporary files, created by the `www-user`. Both
users are in the `www-data` group.
Ticket: https://phabricator.wikimedia.org/T376646
=> Set umask to make files group-writable
