wmde/banner-server

Makefile
composer.json
composer.lock
config/bundles.php
phpcs.xml
src/Kernel.php
symfony.lock

Fix wrong composer version spec introduced in #2
Remove "cli" from phpcs configuration
Make code conform to coding style
Add phpstan to dev requirements
Raise phpstan analysis level to 7.
Add "fix-cs" task to Makefile

Fix code style checks

---

src/Controller/BannerController.php

Avoid having to get the RequestStack, use Request at call time instead.
This gets rid of two internal variables and lowers the risk of
exceptions in the constructor.
See https://symfony.com/doc/current/service_container/3.3-di-changes.html#controllers-are-registered-as-services how this works.

Inject HTTP request in controller action

---

src/Entity/BannerSelection/Bucket.php
src/Entity/BannerSelection/Campaign.php
src/Entity/BannerSelection/CampaignCollection.php

Small follow up in order to unblock the development of BannerSelection UseCase

Add bucket selection to Campaign

---

config/services.yaml

For our "Visitors Survey" banner we want to decrease the seasonal limit
to 1, to show the banner only once to each visitor of wikipedia.de

Decrease seasonal limit

---

src/Controller/BannerSelectionController.php

https://phabricator.wikimedia.org/T224296

Fix Firefox empty banner MIME type mismatch error

---

.gitignore
.travis.yml
build/app/Dockerfile
composer.json
composer.lock
phpstan.neon.dist
src/Controller/BannerSelectionController.php
src/EventListener/ExceptionListener.php
src/Kernel.php
src/UseCase/BannerSelection/BannerSelectionUseCase.php
symfony.lock
tests/Unit/Controller/BannerSelectionControllerTest.php
tests/Unit/Entity/BannerSelection/BannerTest.php
tests/Unit/Entity/BannerSelection/BucketTest.php
tests/Unit/Entity/BannerSelection/CampaignCollectionTest.php
tests/Unit/Entity/BannerSelection/CampaignTest.php
tests/Unit/Entity/BannerSelection/ImpressionThresholdTest.php
tests/Unit/EventListener/ExceptionListenerTest.php
tests/Unit/UseCase/BannerSelection/ActiveBannerSelectionDataTest.php
tests/Unit/UseCase/BannerSelection/BannerSelectionUseCaseTest.php
tests/Unit/UseCase/BannerSelection/EmptyBannerSelectionDataTest.php
tests/Unit/UseCase/BannerSelection/VisitorTest.php
tests/Unit/Utils/CampaignConfigurationLoaderTest.php

This fixes the build errors and updates the dependencies (including PHP), also fixing the security issues.

Update PHP container

---

src/Controller/BannerSelectionController.php
src/Entity/Visitor.php
src/UseCase/BannerSelection/ActiveBannerSelectionData.php
src/UseCase/BannerSelection/BannerSelectionData.php
src/UseCase/BannerSelection/BannerSelectionUseCase.php
src/UseCase/BannerSelection/EmptyBannerSelectionData.php
tests/Fixtures/VisitorFixture.php
tests/Unit/Entity/VisitorTest.php

It was (mis)placed in the use case, now it's a official domain entitity.

Move "Visitor" entity

---

config/routes.yaml
config/services.yaml
src/Controller/DonationFinishedController.php
tests/Unit/Controller/DonationFinishedControllerTest.php

This is for https://phabricator.wikimedia.org/T243616
Please merge #36 first.

Add endpoint to set cookie

---

composer.lock
src/Controller/DonationFinishedController.php
symfony.lock

This should improve 3rd party cookie retention, signaling to the
browsers that we WANT to set a 3rd party cookie. For SameSite=None to
work, the cookie must also be set to "secure".
See https://web.dev/samesite-cookies-explained/
This should improve https://phabricator.wikimedia.org/T243616

Change SameSite cookie setings to 'None'

---

config/routes.yaml
config/services.yaml
src/Controller/AbstractCookieController.php
src/Controller/BannerClosedController.php
src/Controller/DonationFinishedController.php
symfony.lock
tests/Unit/Controller/CookieControllerTest.php
tests/Utils/TestCookieController.php

https://phabricator.wikimedia.org/T243614

Add Cookie with Timout for Banner Closing

---

.scrutinizer.yml

This will hopefully also fix #72

Use PHP 7.4 in Scrutinizer

---

composer.json
composer.lock

Concerns Covers-Validator dependency.
Track status of the bug in this PR: https://github.com/oradwell/covers-validator/issues/28
Should be changed when bug is fixed.

Downgrade phpunit to 2.9.6 to fix CI error

---

composer.lock
src/Utils/CampaignConfigurationLoader.php
tests/Fixtures/campaigns/campaigns.yml
tests/Unit/Utils/CampaignConfigurationLoaderTest.php

- Update dependencies
- Fix nullable display width configuration

fix config reading

---

.env.test
.gitignore
Makefile
composer.json
composer.lock
config/bootstrap.php
config/packages/cache.yaml
config/packages/prod/routing.yaml
config/preload.php
config/routes/dev/framework.yaml
phpunit.xml.dist
symfony.lock
tests/bootstrap.php

This contains framework updates auto-generated by Symfony

Update symfony bootstrap

---

.travis.yml
Makefile
build/travis/uploadCoverage.sh

https://phabricator.wikimedia.org/T284180
This modifies the coverage report uploading so it works in a similar way to the other repositories

Generate coverage report in CI

---

composer.lock
config/routes/framework.yaml

This is mostly to get rid of dependabot PRs.
I also added the http_method_override parameter to the framework config as the default will change on the next major update.
See https://symfony.com/doc/current/reference/configuration/framework.html#http-method-override

Update Composer packages

---

composer.lock

This should replace all the dependabot PRs.

Update all composer dependencies

---

config/services.yaml

Ticket: https://phabricator.wikimedia.org/T349843

Decrease the banner limit from 10 to 7

---

.github/dependabot.yml
.travis.yml
composer.lock
config/packages/framework.yaml

- Update dependencies before re-enabling dependabot

Re-enable dependabot

---

composer.json
composer.lock
tests/Unit/Controller/BannerSelectionControllerTest.php
tests/Unit/Controller/CookieControllerTest.php
tests/Unit/Entity/BannerSelection/BannerTest.php
tests/Unit/Entity/BannerSelection/BucketTest.php
tests/Unit/Entity/BannerSelection/CampaignCollectionTest.php
tests/Unit/Entity/BannerSelection/CampaignTest.php
tests/Unit/Entity/BannerSelection/ImpressionThresholdTest.php
tests/Unit/Entity/VisitorTest.php
tests/Unit/EventListener/ExceptionListenerTest.php
tests/Unit/UseCase/BannerSelection/ActiveBannerSelectionDataTest.php
tests/Unit/UseCase/BannerSelection/BannerSelectionUseCaseTest.php
tests/Unit/UseCase/BannerSelection/EmptyBannerSelectionDataTest.php
tests/Unit/Utils/CampaignConfigurationLoaderTest.php

Ticket: https://phabricator.wikimedia.org/T359971

Update to PHPUnit 11

---

Makefile
docker-compose.yml

- use our own development PHP image for running composer and running the app locally
https://phabricator.wikimedia.org/T378131

Use fun-tech docker image

---

.woodpecker/ci.yml
Makefile
src/UseCase/BannerSelection/BannerSelectionUseCase.php
src/Utils/CampaignConfigurationLoader.php
tests/Unit/EventListener/ExceptionListenerTest.php
tests/Unit/Utils/CampaignConfigurationLoaderTest.php

- Solve errors
Ticket: https://phabricator.wikimedia.org/T359803

Upgrade phpstan level

---

composer.lock
config/routes.yaml
src/Controller/DefaultRouteController.php

- Create a new controller
- Create a new route in routes.yaml
Ticket: https://phabricator.wikimedia.org/T385992

Create new default route

---

.woodpecker/ci.yml
composer.json
composer.lock

Ticket: https://phabricator.wikimedia.org/T387976

 Update php version to `8.4`
